USE dblab5;
SELECT MATCHID, PLAYER FROM GOAL
WHERE TEAMID = 'GER';

SELECT ID, STADIUM, TEAM1, TEAM2 FROM GAME
WHERE ID = 1012;

SELECT PLAYER, TEAMID, STADIUM, MDATE FROM GOAL, GAME
WHERE TEAMID = 'GER';

SELECT PLAYER, TEAM1, TEAM2 FROM GOAL, GAME
WHERE PLAYER LIKE 'Mario%';

SELECT PLAYER, TEAMID, COACH, GTIME FROM GOAL, ETEAM
WHERE GTIME <= 10;

SELECT MDATE, TEAMNAME FROM GAME, ETEAM
WHERE TEAM1 IN (
	SELECT TEAM1 FROM GAME
    WHERE COACH = 'Fernando Santos'
);

SELECT PLAYER FROM GOAL, GAME
WHERE STADIUM = 'National Stadium, Warsaw';

SELECT DISTINCT PLAYER FROM GOAL, GAME
WHERE TEAMID != 'GER' AND (TEAM1 = 'GER' OR TEAM2 = 'GER');

SELECT TEAMNAME, COUNT(*) FROM ETEAM, GOAL
WHERE ID = TEAMID
GROUP BY TEAMNAME;

SELECT STADIUM, COUNT(*) FROM GAME, GOAL
WHERE MATCHID = ID
GROUP BY STADIUM;

SELECT MATCHID, MDATE, COUNT(*) FROM GOAL, GAME
WHERE TEAM1 = 'POL' OR TEAM2 = 'POL'
GROUP BY MATCHID, MDATE;

SELECT MATCHID, MDATE, COUNT(*) FROM GOAL, GAME
WHERE TEAM1 = 'GER' OR TEAM2 = 'GER'
GROUP BY MATCHID, MDATE;


