CREATE DATABASE dblab5;
USE dblab5;
CREATE TABLE ETEAM (
	ID VARCHAR(3) primary key,
    TEAMNAME VARCHAR(100),
    COACH VARCHAR(100)
);

CREATE TABLE GAME (
	ID INT PRIMARY KEY,
    MDATE VARCHAR(12),
    STADIUM VARCHAR(100),
    TEAM1 VARCHAR(100),
    TEAM2 VARCHAR(100)
);

CREATE TABLE GOAL (
	MATCHID INT,
    INDEX(MATCHID),
    CONSTRAINT FK_MATCHID FOREIGN KEY(MATCHID)
    REFERENCES GAME(ID),
    TEAMID VARCHAR(3),
    INDEX(TEAMID),
    CONSTRAINT FK_TEAMID FOREIGN KEY(TEAMID)
    REFERENCES ETEAM(ID),
    PLAYER VARCHAR(100),
    GTIME INT,
    PRIMARY KEY (MATCHID, GTIME)
);

